### ISSUE TITLE
Certain Codelyzer Rules hang linting on angular-cli project after upgrading codelyzer 1.0->2.0 and tslint 3.x->4.x

### ISSUE THREAD

**Issue by JohannesRudolph** [mgechev/codelyzer#181]
See discussion in https://github.com/angular/angular-cli/issues/3404

I could pinpoint it down to these rules, each of which makes linting take forever:
```
     "no-input-rename": true,
    "no-output-rename": true,
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "no-access-missing-member": true,
    "templates-use-public": true,
```

Anyway I can debug into codelyzer live on my project? It's a proprietary codebase, so it's difficult to produce a repro.

**Comment by mgechev** [comment]
The best you can do is to run:

tslint -c tslint.config path/to/file.ts

See which file causes codelyzer to hang and share its content. This way I will be able to debug it and push a fix as soon as possible.

**Comment by mgechev** [comment]
PS: in order to find the file easier you can first locate the directory into which it is located:

tslint -c dir1/**/*.ts
...

**Comment by psurrey** [comment]
I've had the same issue and took the time to go through the files in order to figure out what caused tslint to hang.
Result: We use stylus for our css styles and in one of the *.styl files there was the following line:

`position: relative // relative for .tableConfigs position: absolute"`
changing it to (removing the `"` at the end of the line fixes it):
`position: relative // relative for .tableConfigs position: absolute`

Does codelyzer analyze the styl files as well?

**Comment by mgechev** [comment]
Yeah, it can analyze stylus files as well but by default it doesn't. Take a look at the [advanced configuration](https://github.com/mgechev/codelyzer#advanced-configuration). Currently it thinks of the stylus files as CSS and thins seems to break something.

**Comment by mgechev** [comment]
This seems the issue https://github.com/mgechev/codelyzer/issues/186 and should be already fixed. I'll push the new version tonight.
