### ISSUE TITLE
feature: component-class-suffix give a list of possible suffixes

### ISSUE THREAD

**Issue by pierre-hilt** [mgechev/codelyzer#194]
Hello,

In our project we use several Suffix for our component depending if they are Component or Simple View (so we use Component and View suffix).

It could be great to propose a list of possible suffix for component-class-suffix.

I have already done some code and ready to do a PR if you think that can be a good idea to add this.

```
"component-class-suffix": [true, "Component", "View"]
```

Pierre

**Comment by mgechev** [comment]
Hey @pierre-hilt, we already had [a discussion](https://github.com/mgechev/codelyzer/issues/167) about this. I'm not confident how good idea is it because we're going in a different direction from the official style guide. In the same time we're only expanding the set of features without preventing developers align their codebase to best practices.

I'd love to get a PR with this functionality.

**Comment by pierre-hilt** [comment]
#195

**Comment by pierre-hilt** [comment]
I see that is not compliant with Angular best practices. But I will need to disable completely the rule in my project without this feature.
