### ISSUE TITLE
You can bind only to public class members (templates-use-public)

### ISSUE THREAD

**Issue by Ismaestro** [mgechev/codelyzer#212]
I'm having some troubles with this rule (templates-use-public) and Webstorm. You can see it here:
[http://stackoverflow.com/questions/41622122/tslint-you-can-bind-only-to-public-class-members-templates-use-public](url)

What's the main purpose for this rule? What's wrong?

**Comment by mgechev** [comment]
Hey @Ismaestro! This doesn't seem like an issue in codelyzer. It's not recommended to bind to `private` members because the templates are considered consumers of the components' controller instances (take a look [here](https://github.com/angular/angular/issues/11422) and [here](http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/)).

Also, it seems the WebStorm tslint plugin has similar issue to one recently resolved in the VSCode tslint plugin https://github.com/Microsoft/vscode-tslint/issues/153.
