### ISSUE TITLE
Support for external templates with require

### ISSUE THREAD

**Issue by WiseBird** [mgechev/codelyzer#304]
Feature request.
Please, add support for external templates that are included using webpack's require:
```
    template: require('./component.template.html'),
```

**Comment by mgechev** [comment]
This is an additional syntax which is webpack specific. Angular CLI, for instance, does this inlining as part of the build process. This seems reasonable to me, because you're able to write build system agnostic code and later couple it with the specific bundler.

I think this should be kept outside codelyzer.
