### ISSUE TITLE
Upgrade of codelyzer.com website

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#327]
I think we can upgrade the codelizer.com website : 

- Update npm Packages in package.json (angular 4.X, codelizer 3.X, tslint, ...)
- Update rules used for the editor
- Maybe change the example in the editor
- ... Any ideas ?

**Comment by mgechev** [comment]
I'll be glad to have the newest version of all dependencies in the demo app.

Since the support of external templates/styles, codelyzer is more coupled to node and it will require more work to bundle it as a browser app.

This is something which needs to be done anyway and will require extracting the low-level APIs into a host class (similar to the hosts of the language service of TypeScript).

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.
