### ISSUE TITLE
templates-use-public removed - why? any alternative?

### ISSUE THREAD

**Issue by KKrisu** [mgechev/codelyzer#479]
Hey, I just upgraded to codelyzer 4 and noticed that **templates-use-public** is no longer available. That's a pity because it was very useful for checking AOT compatibility.

Could you explain why it's been removed and whether there is an alternative? Plan to reimplement it maybe?

(I should probably ask this question on slack, although there is already a topic about that created a while ago and very quiet).

Cheers!

**Comment by mgechev** [comment]
More details here https://github.com/mgechev/codelyzer/issues/264

**Comment by pockata-kt** [comment]
Could you please bring this rule back?
As explained here: https://www.rednxt.com/whats-new-in-angular-6/ in angular 6 this is no longer handled by the compiler but still isn't recommended.
It would be very useful because there is currently no way to check this.
Thanks!

**Comment by PRR24** [comment]
Please add it back, was one of the most useful rules for me.

**Comment by lazarljubenovic** [comment]
Why double the work? The `ngc` already handles it. It's not a linting rule anymore, it's simply a compile-time error. You don't have lint rules for invalid JavaScript syntax since it will fail anyway. You don't have lint rules for types with TypeScript because that's what TypeScript is for. Why would you have this as a lint rule now?

**Comment by PRR24** [comment]
I use "open" file-watcher/tsc/systemjs solution for development that is provided by IDE.
For prod build I use ngc --aot that takes place on separate build server.
As a result, development version works perfectly with invalid access rights, but the prod build fails. With the removal of the option developers will find the issue only after code has been commited to VCS and built for release.

**Comment by massimilianorango** [comment]
I really don't understand this choice. 
I use `ng serve` without the `--aot` flag because I want my dev environment to be as fast as possible and JIT compilation is made to achieve this purpose.
During development I also want to be informed as soon as possible if I'm writing code that won't work in production, when I will run `ng build --prod`. I don't want to find it out once I think I'm done but I'm actually not because I have to run `ng serve --aot` and then refactor the code I thought would work.
Am I missing something? I think this is a quite common use case.

**Comment by PRR24** [comment]
I have no good idea, how to force ng serve to highlight errors in the IDE.
Also the project is not angular-cli project and converting it is not feasible at this time.
