### ISSUE TITLE
Feature request: Add rule to prohibit use of document and window

### ISSUE THREAD

**Issue by frederikschubert** [mgechev/codelyzer#51]
As using `window` and `document` prevents the app to be run in a web worker there should be a rule to prohibit the use of them.
This aligns with the rule of not using `ElementRef.nativeElement` for the same reason.
Additionally, but I don't know whether this is possible, the rule should also detect if `window` is implicitly accessed.

**Comment by mgechev** [comment]
The first two are doable. The second one should be defined slightly differently since the renderer accepts as argument the `nativeElement` property of the `ElementRef`. Something like that should work: do not directly access properties and methods of the `nativeElement` property of any object of type `ElementRef`. It won't always rise a warning, for instance:

```ts
...
class Dialog {
  @ViewChild('header') header: ElementRef;
  ngAfterViewInit() {
   // we cast this.header to any so we can't verify that it belongs to ElementRef
    (<any>this.header).nativeElement;
  }
}
...
```

The third one will be very hard/impossible to work in the general case.

**Comment by pierre-hilt** [comment]
Hello,

Maybe BAN rule from TSLint can answer your need:
https://palantir.github.io/tslint/rules/ban/

**Comment by mgechev** [comment]
Yeah, `ban` seems like a good way to limit the usage of some APIs which directly mutate the DOM.
