### ISSUE TITLE
[Feature Request] Component Selector Required

### ISSUE THREAD

**Issue by sam-s4s** [mgechev/codelyzer#551]
Quick feature request... I'd love it if there was a rule I could enable that would force people to always include a selector for any @Component. Currently if it's for a dialog (dynamically created component) or routed page, you don't technically need one, but it makes the DOM a bit messy.

Perhaps it could be added to the existing component-selector rule?

**Comment by wKoza** [comment]
Hi,
What do you think when you say "but it makes the DOM a bit messy." ?

**Comment by lazarljubenovic** [comment]
It's difficult to debug or get around it at all, since the selector which Angular uses for components without a selector is `ng-component`.

Since you don't need it for any dynamic component, including things such as modals, flash messages and routes, you could easily end up with something like the following.

```html
<ng-component>
  <h1>Title</h1>
  <nav> ... </nav>
  <ng-component>
    <h2>Subtitle</h2>
    <p> ... </p>
  </ng-component>
  <ng-component>
    Modal
  </ng-component>
</ng-component>
```

**Comment by wKoza** [comment]
Ok. It makes sense :+1:  . Adding this check to `component-selector` is an option since his rationale:

>Components are easy to identify in the DOM 

but, this rule is embedeed with Angular CLI and we are dealing with a Breaking change... 
So, we should add an option that active the check like this:


 "component-selector": [true, "element", "app", "kebab-case", **_true_**]
