### ISSUE TITLE
Rule "no-life-cycle-call" does not allow for subclassing

### ISSUE THREAD

**Issue by jscharett** [mgechev/codelyzer#573]
If I extend a component and I override a lifecycle hook, this rule prevents me from calling the super method.  While I agree with the premise of the rule, it should, however, allow me to call the super method when overriding.

**Comment by rafaelss95** [comment]
IMHO, this `rule` should prevent this as it does right now because any parent's lifecycle should be called by `Angular` itself. See https://github.com/angular/angular/issues/23091 and its related issues.

**Comment by mgechev** [comment]
@jscharett makes sense to me. @rafaelss95 would you want to check if the receiver of the method call isn't `super`?

**Comment by kevinphelps** [comment]
@rafaelss95: If I understand correctly, the issue you linked to is a bug where Angular does not call a lifecycle hook that is defined in a TypeScript mixin, not a base class.

Consider the following:

```
class BaseComponent {
  ngOnInit() {
    console.log('base component init');
  }
}

@Component({})
class MyComponent {
  ngOnInit() {
    super.ngOnInit();
    console.log('my component init');
  }
}
```

The `super.ngOnInit();` line should be allowed by the "no-lifecycle-call" rule because that is ONLY way `BaseComponent#ngOnInit` can be called in this case.

If you don't provide an implementation of `ngOnInit` in `MyComponent`, `BaseComponent#ngOnInit` would be invoked when Angular invokes `MyComponent#ngOnInit` simply because of how `extends` works.

But when you override a method, the outside world (i.e Angular) cannot cannot and should not call the super implementation.

**Comment by rafaelss95** [comment]
You're totally right. I misread the issue. Good catch :)

**Comment by kevinphelps** [comment]
If both classes are decorated, it works differently.
