### ISSUE TITLE
export NgWalker for library users

### ISSUE THREAD

**Issue by piyukore06** [mgechev/codelyzer#657]
Hello Maintainers,

Thank you for building Codelyzer. It is really helpful not just for catching lint errors but also knowing what is a good way of doing a certain thing.
 
TsLint has exported it's Walkers. On top of which devs can build custom TsLint rules. I wanted to build a custom rule using angular metadata but I found out that NgWalker is not exported.

Is there any particular reason it was not exported?
I am really new at this so if there is any other way of doing the same, pls let me know.

**Comment by mgechev** [comment]
Hey @piyukore06, I've thought of externalizing the `NgWalker` several times. Your proposal makes a lot of sense. To prioritize this feature request, I'll add `votes needed` label and close it, so that people can vote and we can introduce it as part of the roadmap if the demand is high. Alternatively, if you have some time, we'd love to get a PR from you!

**Comment by rafaelss95** [comment]
@mgechev Let's remove the 'votes needed` label from issues that have already been finalized? It's a little confusing...
