### ISSUE TITLE
Feature request: Inverse of no-template-call-expression

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#683]
It would be useful to avoid too much logic in template, keeping it as clean and readable.

An example:

```HTML
<div *ngIf="(a === 1 || b === 2) && c === 'hey'"> // warnings reported
  Something
</div>
```

vs

```HTML
<div *ngIf="canShowSomething()"> // passes
  Something
</div>
```

**Comment by lazarljubenovic** [comment]
Just before someone tells how the second snippet is "wrong"... People freak out about calling functions in templates ("because perf") but then they go ahead and write things like in the first snippet.

Perf-wise, assuming the function does the same logic like the first snippet, are completely equivalent. It's probably no harm if you functions are lean. Also there's no harm if you cache them. So calling functions in templates by itself is not bad, but doing so irresponsibly is.
