### ISSUE TITLE
Codelyzer doesn't support export default

### ISSUE THREAD

**Issue by wKoza** [mgechev/codelyzer#778]
I reedit [my comment](https://github.com/mgechev/codelyzer/pull/754#discussion_r258851555) form the PR #754.

If we create a simple class like that:

```ts
export default class { ... }
```

and we launch `ng lint`, we have a big big crash [here] (https://github.com/mgechev/codelyzer/blob/master/src/propertyDecoratorBase.ts#L41) and many other places !

**Comment by mgechev** [comment]
That's probably in the Angular router where we collect the metadata?

**Comment by wKoza** [comment]
Each call to `visitClassDeclaration` is often following by `node.name!.text`, [here](https://github.com/mgechev/codelyzer/blob/5e067a1857fea1b609b6eb44340fd31619ec1526/src/selectorNameBase.ts#L105) or [there](https://github.com/mgechev/codelyzer/blob/a23ccde36de2b76ea7aa218458fd17a03d4f4a92/src/componentChangeDetectionRule.ts#L39) and without name ... it's the crash
I'll do a complete check tomorrow.

**Comment by rafaelss95** [comment]
I agree that instead of using the non-null assertion operator, we should check all these properties correctly!

However, I disagree on the point of returning class names (not just class names) in failure messages because I don't see much value in returning them since the `lint` already returns the exact line where _failure_ occurred accompanied by a (descriptive) message.

I really prefer to return generic/direct messages without polluting the output with class/variable names, as TSLint does, for example.

**Comment by wKoza** [comment]
I didn't go much more deeper into the analyse. But, I can say that a class with a decorator and no name should be throw an error.
@rafaelss95 , your idea is interesting. A generic message allows to make statistic easily.

**Comment by mgechev** [comment]
@rafaelss95 yes, this makes sense.
