### ISSUE TITLE
Feature request: Avoid using Angular's directives add input name

### ISSUE THREAD

**Issue by samuelfernandez** [mgechev/codelyzer#949]
Imagine a component that by mistake uses an input with the name `routerLink`. In the parent it would be used like `<comp [routerLink]="...">`, which will add Angular's directive, something wrong. I feel having a linter that checks input names and has a blacklist of Angular's directives to warn about misuses could be useful.

**Comment by samuelfernandez** [comment]
I can try to submit a PR if approved.

**Comment by lazarljubenovic** [comment]
Such a rule would, in its most general form, allow for providing a blacklist of input names. Then we could have some pre-defined configurations like "standard", which would include a bunch of DOM properties, things from `@angular/forms` like `formGroup`, `formGroupName`, things from `@angular/router` like `routerLink`, etc.

Note, however, that Angular's selector mechanism was specifically designed to allow this kind of behavior. For example, it's common to define selectors such as `something[formControlName],something[formControl]`, implying that, when `something` is used as a reactive form control, _something else_ will happen as well. Inside such as component, you usually purposely grab the `@Input() formControl` in order to do something with it.

There aren't many directives with inputs in Angular. IMO it probably makes more sense to learn them all as part of learning the framework itself, and then use it smartly, instead of forbidding its usage. Unless, of course, you have reasons to believe this is an anti-pattern and want to stop yourself (and the team) from using it, which is the point of having a linter in the first place.

**Comment by rafaelss95** [comment]
Not sure I got the point of this issue, but it sounds like what I suggested in #668, no?

**Comment by mgechev** [comment]
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Comment by samuelfernandez** [comment]
@rafaelss95 You are right, #668 should cover this one.
